import { z } from "zod";

import {
  ALLOWED_AUDIO_MIME_TYPES,
  MAX_AUDIO_BYTES,
  MAX_AUDIO_DURATION_MS,
} from "@/lib/supabase/config";
import { AUDIO_ENHANCEMENT_PRESETS } from "@/types/domain";

import { uuidSchema } from "./common";

/**
 * Waveform peaks as produced by the worker. Kept small on purpose — this is
 * stored inline in Postgres and shipped to every client that renders the card.
 */
export const waveformPeaksSchema = z.object({
  version: z.literal(1),
  bits: z.literal(8),
  samples_per_pixel: z.number().int().min(1),
  data: z.array(z.number().int().min(0).max(255)).min(1).max(4000),
});

/**
 * Registering an uploaded/recorded file.
 *
 * NOTE: `mime_type` here is a client claim. It narrows what we accept, but the
 * authoritative check is the magic-byte sniff performed server-side before the
 * asset row is created (spec s18). See docs/AUDIO_ARCHITECTURE.md.
 */
export const createAudioAssetSchema = z.object({
  /** Pre-generated by the caller so the storage path can embed it before the row exists (see `createUploadTicket`). */
  id: uuidSchema.optional(),
  original_path: z.string().min(1).max(1024),
  mime_type: z.enum(ALLOWED_AUDIO_MIME_TYPES),
  byte_size: z.number().int().positive().max(MAX_AUDIO_BYTES),
  duration_ms: z.number().int().positive().max(MAX_AUDIO_DURATION_MS).nullish(),
  sample_rate: z.number().int().positive().max(192_000).nullish(),
  channels: z.number().int().min(1).max(2).nullish(),
  enhancement_preset: z.enum(AUDIO_ENHANCEMENT_PRESETS).default("natural"),
  checksum_sha256: z
    .string()
    .regex(/^[0-9a-f]{64}$/, "Expected a lowercase hex SHA-256 digest")
    .nullish(),
});

/** Mirrors `ADVANCED_EQ_BANDS`/`ADVANCED_EQ_MAX_GAIN_DB` in `src/lib/audio/enhancement.ts`. */
export const advancedEqSettingsSchema = z.object({
  60: z.number().min(-12).max(12),
  250: z.number().min(-12).max(12),
  1000: z.number().min(-12).max(12),
  4000: z.number().min(-12).max(12),
  12000: z.number().min(-12).max(12),
});

/**
 * `createUploadTicket` Server Action input (spec §18, §36). The client
 * already knows `mimeType`/`sizeBytes`/`durationMs` from the captured Blob
 * and the preset/EQ chosen in the enhance step — none of this is trusted as
 * final, it only narrows what gets a signed upload URL at all. The server
 * re-validates the file's actual bytes in `finalizeUpload`.
 */
export const createUploadTicketSchema = z.object({
  mimeType: z.enum(ALLOWED_AUDIO_MIME_TYPES),
  sizeBytes: z.number().int().positive().max(MAX_AUDIO_BYTES),
  durationMs: z.number().int().positive().max(MAX_AUDIO_DURATION_MS).nullish(),
  creationType: z.enum(["recorded", "uploaded"]),
  enhancementPreset: z.enum(AUDIO_ENHANCEMENT_PRESETS).default("natural"),
});

/**
 * `advancedEq` travels here rather than on `createUploadTicket` because it is
 * only needed once, right before the processing job is enqueued — carrying
 * it through both actions would mean persisting client-chosen state
 * server-side between two independent round trips for no benefit.
 */
export const finalizeUploadSchema = z.object({
  assetId: uuidSchema,
  advancedEq: advancedEqSettingsSchema.nullish(),
});

export const enqueueProcessingSchema = z.object({
  audioAssetId: uuidSchema,
  preset: z.enum(AUDIO_ENHANCEMENT_PRESETS).default("natural"),
});

export const enqueueDuetMixSchema = z.object({
  /** The new take recorded against the original. */
  audioAssetId: uuidSchema,
  /** The original Wave's audio, used as the reference stem. */
  referenceAssetId: uuidSchema,
  /**
   * Start of the new take relative to the reference, in milliseconds.
   * Negative values are rejected: the contribution cannot start before the
   * reference does. See docs/DUET_SPEC.md.
   */
  offsetMs: z.number().int().min(0).max(MAX_AUDIO_DURATION_MS),
  preset: z.enum(AUDIO_ENHANCEMENT_PRESETS).default("studio"),
});

export type WaveformPeaksInput = z.infer<typeof waveformPeaksSchema>;
export type CreateAudioAssetInput = z.infer<typeof createAudioAssetSchema>;
export type AdvancedEqSettingsInput = z.infer<typeof advancedEqSettingsSchema>;
export type CreateUploadTicketInput = z.infer<typeof createUploadTicketSchema>;
export type FinalizeUploadInput = z.infer<typeof finalizeUploadSchema>;
export type EnqueueProcessingInput = z.infer<typeof enqueueProcessingSchema>;
export type EnqueueDuetMixInput = z.infer<typeof enqueueDuetMixSchema>;
