import { z } from "zod";

import {
  ALLOWED_AUDIO_MIME_TYPES,
  MAX_AUDIO_BYTES,
  MAX_AUDIO_DURATION_MS,
} from "@/lib/supabase/config";
import { AUDIO_ENHANCEMENT_PRESETS } from "@/types/domain";

import { uuidSchema } from "./common";

/**
 * The six free presets plus the two AKINTI Pro sounds (`pitch_snap`/
 * `self_harmony` — `PRO_ENHANCEMENT_PRESETS` in `src/lib/audio/enhancement.ts`,
 * now valid `audio_enhancement_preset` enum values as of migration
 * `20260906120000_pro_presets_pitch.sql`). Kept as a literal list rather than
 * importing from `enhancement.ts` to avoid a validation-module ->
 * client-preview-module dependency; `isProOnlyEnhancementPresetId` (called
 * from `create/actions.ts` BEFORE this schema runs) is the actual Pro gate —
 * this list only decides what shape of string is accepted at all.
 */
const ALL_AUDIO_ENHANCEMENT_PRESET_IDS = [
  ...AUDIO_ENHANCEMENT_PRESETS,
  "pitch_snap",
  "self_harmony",
] as const;

/**
 * `MediaRecorder.mimeType` (and therefore `Blob.type` / `RecorderResult.mimeType`
 * — see `getRecordingMimeType` in `src/lib/audio/capabilities.ts`) reports codec
 * parameters, e.g. `"audio/webm;codecs=opus"` — real, live behavior in every
 * engine that supports Opus/WebM or AAC/MP4 recording, not an edge case.
 * `ALLOWED_AUDIO_MIME_TYPES` (`src/lib/supabase/config.ts`) is deliberately the
 * bare container type list; without stripping the parameter first, EVERY real
 * recording made through the browser's actual MediaRecorder failed this
 * validation outright (`z.enum` requires an exact match) — confirmed directly
 * against a live Chromium recording, spec §17/§18/§36. Uploaded files (picked
 * from disk, `file.type`) are already bare and pass through unchanged.
 */
export const audioMimeTypeSchema = z.preprocess(
  (value) => (typeof value === "string" ? value.split(";")[0]!.trim().toLowerCase() : value),
  z.enum(ALLOWED_AUDIO_MIME_TYPES),
);

/**
 * Waveform peaks as produced by the worker. Kept small on purpose — this is
 * stored inline in Postgres and shipped to every client that renders the card.
 */
export const waveformPeaksSchema = z.object({
  version: z.literal(1),
  bits: z.literal(8),
  samples_per_pixel: z.number().int().min(1),
  data: z.array(z.number().int().min(0).max(255)).min(1).max(4000),
});

/**
 * Registering an uploaded/recorded file.
 *
 * NOTE: `mime_type` here is a client claim. It narrows what we accept, but the
 * authoritative check is the magic-byte sniff performed server-side before the
 * asset row is created (spec s18). See docs/AUDIO_ARCHITECTURE.md.
 */
export const createAudioAssetSchema = z.object({
  /** Pre-generated by the caller so the storage path can embed it before the row exists (see `createUploadTicket`). */
  id: uuidSchema.optional(),
  original_path: z.string().min(1).max(1024),
  mime_type: audioMimeTypeSchema,
  byte_size: z.number().int().positive().max(MAX_AUDIO_BYTES),
  duration_ms: z.number().int().positive().max(MAX_AUDIO_DURATION_MS).nullish(),
  sample_rate: z.number().int().positive().max(192_000).nullish(),
  channels: z.number().int().min(1).max(2).nullish(),
  enhancement_preset: z.enum(ALL_AUDIO_ENHANCEMENT_PRESET_IDS).default("natural"),
  checksum_sha256: z
    .string()
    .regex(/^[0-9a-f]{64}$/, "Expected a lowercase hex SHA-256 digest")
    .nullish(),
});

/** Mirrors `ADVANCED_EQ_BANDS`/`ADVANCED_EQ_MAX_GAIN_DB` in `src/lib/audio/enhancement.ts`. */
export const advancedEqSettingsSchema = z.object({
  60: z.number().min(-12).max(12),
  250: z.number().min(-12).max(12),
  1000: z.number().min(-12).max(12),
  4000: z.number().min(-12).max(12),
  12000: z.number().min(-12).max(12),
});

/**
 * `createUploadTicket` Server Action input (spec §18, §36). The client
 * already knows `mimeType`/`sizeBytes`/`durationMs` from the captured Blob
 * and the preset/EQ chosen in the enhance step — none of this is trusted as
 * final, it only narrows what gets a signed upload URL at all. The server
 * re-validates the file's actual bytes in `finalizeUpload`.
 */
export const createUploadTicketSchema = z.object({
  mimeType: audioMimeTypeSchema,
  sizeBytes: z.number().int().positive().max(MAX_AUDIO_BYTES),
  durationMs: z.number().int().positive().max(MAX_AUDIO_DURATION_MS).nullish(),
  creationType: z.enum(["recorded", "uploaded"]),
  enhancementPreset: z.enum(ALL_AUDIO_ENHANCEMENT_PRESET_IDS).default("natural"),
});

/**
 * `advancedEq` travels here rather than on `createUploadTicket` because it is
 * only needed once, right before the processing job is enqueued — carrying
 * it through both actions would mean persisting client-chosen state
 * server-side between two independent round trips for no benefit.
 *
 * `skipAutoProcessing` closes the Duet job race documented in
 * `docs/DUET_SPEC.md`/`docs/AUDIO_ARCHITECTURE.md`: a Duet contribution stem
 * is about to be consumed by a `mix_duet` job (enqueued separately by
 * `publishDuetWave`, `src/app/(app)/create/duetActions.ts`) that already
 * applies the chosen preset/EQ to it as part of the mixdown. Also enqueuing
 * the ordinary standalone `process_audio` job for the same asset would race
 * `mix_duet` to write `audio_assets`/`complete_audio_job` last — both jobs
 * target the same row, and unlike `mix_duet` vs. `mix_duet`, they are
 * different `job_type`s so the one-live-job-per-`(asset, job_type)` unique
 * index does not prevent the race. Defaults to `false` so every other
 * caller (`CreateFlow.tsx`'s ordinary Recorded/Uploaded publish) is
 * unaffected.
 */
export const finalizeUploadSchema = z.object({
  assetId: uuidSchema,
  advancedEq: advancedEqSettingsSchema.nullish(),
  skipAutoProcessing: z.boolean().optional().default(false),
});

export const enqueueProcessingSchema = z.object({
  audioAssetId: uuidSchema,
  preset: z.enum(AUDIO_ENHANCEMENT_PRESETS).default("natural"),
});

export const enqueueDuetMixSchema = z.object({
  /** The new take recorded against the original. */
  audioAssetId: uuidSchema,
  /** The original Wave's audio, used as the reference stem. */
  referenceAssetId: uuidSchema,
  /**
   * Start of the new take relative to the reference, in milliseconds.
   * Negative values are rejected: the contribution cannot start before the
   * reference does. See docs/DUET_SPEC.md.
   */
  offsetMs: z.number().int().min(0).max(MAX_AUDIO_DURATION_MS),
  preset: z.enum(AUDIO_ENHANCEMENT_PRESETS).default("studio"),
});

export type WaveformPeaksInput = z.infer<typeof waveformPeaksSchema>;
export type CreateAudioAssetInput = z.infer<typeof createAudioAssetSchema>;
export type AdvancedEqSettingsInput = z.infer<typeof advancedEqSettingsSchema>;
export type CreateUploadTicketInput = z.infer<typeof createUploadTicketSchema>;
export type FinalizeUploadInput = z.infer<typeof finalizeUploadSchema>;
export type EnqueueProcessingInput = z.infer<typeof enqueueProcessingSchema>;
export type EnqueueDuetMixInput = z.infer<typeof enqueueDuetMixSchema>;
