import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Python virtualenv / vendored deps for sidecar/ (sidecar/README.md) —
    // never JS/TS, and large enough that lint had no business walking them.
    "sidecar/.venv/**",
    "sidecar/**/site-packages/**",
    // Generated by `serwist build` (`serwist.config.mjs`) from
    // `src/app/sw.ts` — a minified build artifact, same category as
    // `.next/**` above, not hand-authored code.
    "public/sw.js",
  ]),
]);

export default eslintConfig;
