"""Startup capability detection for the AKINTI audio sidecar.

Every DSP feature this service offers has a real dependency that may or may
not be installable on a given machine (DeepFilterNet3's `deepfilterlib`
needs a Rust toolchain to build from source on Windows; Matchering is
GPL-3.0 and pure Python/numpy so it installs everywhere). Rather than let an
import fail deep inside a request handler, every optional dependency is
probed once at import time here, and `GET /health` reports exactly what is
real -- this module must never claim a capability is available when the
underlying import failed (see the repo-wide "never fake success" rule in
docs/AUDIO_ARCHITECTURE.md, which this sidecar mirrors for its own surface).
"""

from __future__ import annotations

import shutil
import subprocess
from dataclasses import dataclass
from functools import lru_cache
from pathlib import Path

SIDECAR_ROOT = Path(__file__).resolve().parent.parent
RNNOISE_MODEL_PATH = SIDECAR_ROOT / "models" / "rnnoise.rnnn"
REFERENCE_DIR = SIDECAR_ROOT / "reference"


def _probe_import(module_name: str) -> bool:
    try:
        __import__(module_name)
        return True
    except Exception:
        # Any failure (missing module, missing native extension, a Rust
        # toolchain error surfaced at import time) means "not available" --
        # never partially trust an import that raised.
        return False


def _probe_ffmpeg() -> bool:
    binary = shutil.which("ffmpeg")
    if not binary:
        return False
    try:
        result = subprocess.run(
            [binary, "-version"], capture_output=True, timeout=5, check=False
        )
        return result.returncode == 0
    except Exception:
        return False


@dataclass(frozen=True)
class Capabilities:
    ffmpeg: bool
    deepfilternet: bool
    arnndn: bool
    matchering: bool
    librosa: bool
    soundfile: bool

    def as_dict(self) -> dict[str, bool]:
        return {
            "ffmpeg": self.ffmpeg,
            "deepfilternet": self.deepfilternet,
            "arnndn": self.arnndn,
            "matchering": self.matchering,
            "librosa": self.librosa,
            "soundfile": self.soundfile,
        }


@lru_cache(maxsize=1)
def detect_capabilities() -> Capabilities:
    """Run every probe exactly once per process and cache the result.

    `arnndn` (ffmpeg's built-in RNNoise filter) additionally requires the
    bundled model file to exist on disk -- ffmpeg ships no default model, so
    without `sidecar/models/rnnoise.rnnn` the filter cannot actually run even
    though ffmpeg itself is present.
    """
    ffmpeg_ok = _probe_ffmpeg()
    return Capabilities(
        ffmpeg=ffmpeg_ok,
        deepfilternet=_probe_import("df"),
        arnndn=ffmpeg_ok and RNNOISE_MODEL_PATH.is_file(),
        matchering=_probe_import("matchering"),
        librosa=_probe_import("librosa"),
        soundfile=_probe_import("soundfile"),
    )


def reference_path_for_family(family: str) -> Path:
    """Bundled placeholder reference master for a preset family.

    These are synthesized (pink-noise-derived, loudness-normalized) stand-ins
    generated by `sidecar/reference/` at repo setup time -- AKINTI does not
    bundle a licensed commercial master. They give Matchering a real
    stereo/EQ/loudness target to match against so the endpoint is genuinely
    functional today; swapping in a licensed reference track per genre later
    requires no code change, only replacing the file. See sidecar/README.md.
    """
    mapping = {
        "bright": REFERENCE_DIR / "bright.wav",
        "warm": REFERENCE_DIR / "warm.wav",
        "balanced": REFERENCE_DIR / "balanced.wav",
    }
    path = mapping.get(family, mapping["balanced"])
    if not path.is_file():
        raise FileNotFoundError(f"reference master not found: {path}")
    return path
