import type { MetadataRoute } from "next";

import { BRAND, BRAND_DESCRIPTION, BRAND_TAGLINE, SITE } from "@/config/terminology";

/**
 * Web app manifest (`docs/PRODUCT_V2.md` §4: "Serwist, install prompt after
 * first publish, ... standalone-mode fixes for iOS").
 *
 * Colours are the design tokens' dark pairing (`docs/design/DESIGN_DNA.json`,
 * `src/app/globals.css`) — graphite ground, paper ink — matching the icon set
 * generated by `scripts/generate-icons.mjs` so the splash screen a browser
 * synthesizes from `background_color` + the largest icon never mismatches.
 * `lang` mirrors `SITE.htmlLang` (`src/app/layout.tsx`'s `<html lang>`) rather
 * than being hardcoded a second time.
 */
export default function manifest(): MetadataRoute.Manifest {
  return {
    id: "/",
    name: `${BRAND} — ${BRAND_TAGLINE}`,
    short_name: BRAND,
    description: BRAND_DESCRIPTION,
    lang: SITE.htmlLang,
    start_url: "/",
    scope: "/",
    display: "standalone",
    orientation: "portrait-primary",
    background_color: "#131412",
    theme_color: "#131412",
    icons: [
      {
        src: "/favicon.ico",
        sizes: "any",
        type: "image/x-icon",
      },
      {
        src: "/icons/icon-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icons/icon-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icons/icon-maskable-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  };
}
