import type { MetadataRoute } from "next";
import { getLocale, getTranslations } from "next-intl/server";

/**
 * Web app manifest (`docs/PRODUCT_V2.md` §4: "Serwist, install prompt after
 * first publish, ... standalone-mode fixes for iOS").
 *
 * Colours are the design tokens' dark pairing (`docs/design/DESIGN_DNA.json`,
 * `src/app/globals.css`) — graphite ground, paper ink — matching the icon set
 * generated by `scripts/generate-icons.mjs` so the splash screen a browser
 * synthesizes from `background_color` + the largest icon never mismatches.
 * `lang`/`name`/`description` are resolved the same way `src/app/layout.tsx`
 * resolves `<html lang>` and its metadata (`src/i18n/request.ts`), so a
 * Turkish browser sees a Turkish install prompt. The separator is `·`, not
 * an em dash, matching the copy rule the rest of the product follows
 * (`docs/design/DESIGN.md` §12).
 */
export default async function manifest(): Promise<MetadataRoute.Manifest> {
  const [locale, t] = await Promise.all([getLocale(), getTranslations("Manifest")]);

  return {
    id: "/",
    name: t("name"),
    short_name: t("shortName"),
    description: t("description"),
    lang: locale,
    start_url: "/",
    scope: "/",
    display: "standalone",
    orientation: "portrait-primary",
    background_color: "#131412",
    theme_color: "#131412",
    icons: [
      {
        src: "/favicon.ico",
        sizes: "any",
        type: "image/x-icon",
      },
      {
        src: "/icons/icon-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icons/icon-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icons/icon-maskable-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  };
}
