#!/usr/bin/env node
/**
 * Generates the PWA icon set from a single waterline-mark SVG (§ DESIGN.md:
 * "one drawing primitive, the waterline" — the mark is the same amplitude
 * trace used everywhere else in the product, not a separate logo).
 *
 * `sharp` (already present in `node_modules` — a transitive dependency, not
 * a new one added for this) rasterizes the SVG to PNG; no heavy new
 * dependency (`docs/research/libraries.md`: never add one without a reason).
 *
 * Run with `node scripts/generate-icons.mjs`. Not wired into `npm run build`
 * — the output is committed to `public/icons/`, regenerated by hand only
 * when the mark itself changes.
 */

import { mkdir, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

import sharp from "sharp";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const OUT_DIR = path.join(__dirname, "..", "public", "icons");

// Design tokens (`docs/design/DESIGN_DNA.json` / `src/app/globals.css`):
// graphite ground, paper mark — the dark-theme pairing, used for the icon so
// it reads on both a light and a dark home-screen/dock background.
const GRAPHITE = "#131412";
const PAPER = "#efefec";

/**
 * A simple amplitude trace (the waterline) centred in the square: a smooth
 * polyline with a few peaks, drawn as a single stroked path — the same
 * primitive that renders every waveform, progress bar and separator in the
 * product (DESIGN.md §5). `safeInset` keeps the trace inside the ~80% safe
 * zone maskable icons require (https://serwist.pages.dev has no opinion on
 * this — it's the W3C/Android adaptive-icon spec).
 */
function waterlineSvg({ size, safeInset, background, stroke }) {
  const inset = size * safeInset;
  const w = size - inset * 2;
  const midY = size / 2;
  const amp = w * 0.16;
  const x0 = inset;
  const x1 = inset + w * 0.22;
  const x2 = inset + w * 0.4;
  const x3 = inset + w * 0.5;
  const x4 = inset + w * 0.6;
  const x5 = inset + w * 0.78;
  const x6 = inset + w;
  const strokeWidth = Math.max(2, size * 0.045);

  const path = [
    `M ${x0} ${midY}`,
    `L ${x1} ${midY}`,
    `L ${x2} ${midY - amp}`,
    `L ${x3} ${midY + amp * 1.4}`,
    `L ${x4} ${midY - amp * 0.6}`,
    `L ${x5} ${midY}`,
    `L ${x6} ${midY}`,
  ].join(" ");

  return `<svg width="${size}" height="${size}" viewBox="0 0 ${size} ${size}" xmlns="http://www.w3.org/2000/svg">
  <rect width="${size}" height="${size}" fill="${background}" />
  <path d="${path}" fill="none" stroke="${stroke}" stroke-width="${strokeWidth}" stroke-linecap="round" stroke-linejoin="round" />
</svg>`;
}

async function renderPng(svg, size, file) {
  const buffer = await sharp(Buffer.from(svg)).resize(size, size).png().toBuffer();
  await writeFile(path.join(OUT_DIR, file), buffer);
  console.log(`wrote ${file} (${size}x${size})`);
}

async function main() {
  await mkdir(OUT_DIR, { recursive: true });

  // Standard icons: a generous safe inset so the mark doesn't crowd the
  // corners even on platforms that don't crop to a mask.
  await renderPng(waterlineSvg({ size: 192, safeInset: 0.22, background: GRAPHITE, stroke: PAPER }), 192, "icon-192.png");
  await renderPng(waterlineSvg({ size: 512, safeInset: 0.22, background: GRAPHITE, stroke: PAPER }), 512, "icon-512.png");

  // Maskable: Android/adaptive-icon masks crop to a circle inscribed in the
  // square, so content must live inside the ~80% "safe zone" — a larger
  // inset than the plain icons above.
  await renderPng(waterlineSvg({ size: 512, safeInset: 0.3, background: GRAPHITE, stroke: PAPER }), 512, "icon-maskable-512.png");

  // Apple touch icon: iOS ignores alpha and rounds the corners itself, so
  // this is simply an opaque 180x180 square.
  await renderPng(waterlineSvg({ size: 180, safeInset: 0.22, background: GRAPHITE, stroke: PAPER }), 180, "apple-touch-icon.png");

  console.log("Icons written to", OUT_DIR);
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
